version: '3.8'
services:
  hub-db_1:
    container_name: pg_hub_1
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hub
    volumes:
      - db_1:/data/postgres
      - ./sql/hubone.sql:/docker-entrypoint-initdb.d/hubone.sql
    ports:
      - '5432:5432'

  hub-db_2:
    container_name: pg_hub_2
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres_2
      - POSTGRES_PASSWORD=postgres_2
      - POSTGRES_DB=hub_2
    volumes:
      - db_2:/data/postgres
      - ./sql/hubtwo.sql:/docker-entrypoint-initdb.d/hubtwo.sql
    ports:
      - '5433:5432'

volumes:
  db_1:
  db_2:
