server:
  compression:
    enabled: true
    mime-types: application/json
  shutdown: graceful

spring:
  application:
    name: The Hub
  datasource:
    hubone:
      url: 'jdbc:postgresql://localhost:5432/hub'
      username: postgres
      password: postgres
    hubtwo:
      url: 'jdbc:postgresql://localhost:5433/hub_2'
      username: postgres_2
      password: postgres_2
    
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: when_authorized
      show-components: when_authorized
      probes:
        enabled: true
    env:
      show-values: when_authorized
    configprops:
      show-values: when_authorized
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true

error:
  stacktrace: false