server:
  compression:
    enabled: true
    mime-types: application/json
  shutdown: graceful

spring:
  application:
    name: The Hub
  datasource:
    url: 'jdbc:postgresql://localhost:5432/hub'
    username: postgres
    password: postgres
    hikari:
      # https://vladmihalcea.com/why-you-should-always-use-hibernate-connection-provider_disables_autocommit-for-resource-local-jpa-transactions/
      # in combination with jpa.properties.hibernate.connection.provider_disables_autocommit: true
      auto-commit: false
  jpa:
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
        jdbc:
          time_zone: UTC
    open-in-view: false
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: when_authorized
      show-components: when_authorized
      probes:
        enabled: true
    env:
      show-values: when_authorized
    configprops:
      show-values: when_authorized
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true

error:
  stacktrace: false